version: '3'

services:
  react_dev:
    build: '.'
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - ${PORT}:3000
    command: yarn start

  softethervpn_server:
    build: '../../../../..'
    ports:
      - 5555:5555
